# Generated by Django 4.1.4 on 2023-01-08 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_remove_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='section_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.section'),
        ),
        migrations.AddField(
            model_name='product',
            name='section_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.section'),
        ),
    ]
