# Generated by Django 4.1.4 on 2023-03-01 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_section_category_section_id_product_section_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items', models.CharField(max_length=5000)),
                ('customer_name', models.CharField(max_length=50)),
                ('order_total', models.IntegerField(default=0)),
                ('order_date', models.DateField()),
                ('customer_phone', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999)])),
            ],
        ),
    ]
