# Generated by Django 4.1.4 on 2023-03-21 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='default_ship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_default', to='shop.address'),
        ),
    ]
