# Generated by Django 4.1.4 on 2023-04-03 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
