# Generated by Django 4.1.4 on 2023-04-03 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_against',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
