# Generated by Django 4.1.4 on 2023-04-04 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_order_delivery_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_code', models.IntegerField(choices=[(1, 'Placed'), (0, 'Cancelled')], default=1)),
                ('status', models.CharField(choices=[('placed', 'Order Placed'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('dispatched', 'Dispatched'), ('shipped', 'Shipped'), ('in-transit', 'In-Transit'), ('out for delivery', 'Out for Delivery'), ('delivered', 'Delivered')], default='placed', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='track_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.track'),
        ),
    ]
