# Generated by Django 4.1.4 on 2023-04-04 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_track_orderitem_track_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='track_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.track'),
        ),
    ]
