# Generated by Django 4.1.4 on 2023-04-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_orderitem_track_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='item_code',
            field=models.IntegerField(choices=[(1, 'Placed'), (0, 'Cancelled'), (2, 'Completed')], default=1),
        ),
    ]
