# Generated by Django 4.1.4 on 2023-04-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_track_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='status',
            field=models.CharField(choices=[('placed', 'Order Placed'), ('packed', 'Packed'), ('dispatched', 'Dispatched'), ('shipped', 'Shipped'), ('in-transit', 'In-Transit'), ('out for delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='placed', max_length=20),
        ),
    ]
